### ISSUE TITLE
video output is on 25 tiled images

### ISSUE THREAD

**Issue by sugizo** [imageio/imageio-ffmpeg#106]
**code**
```
from imageio_ffmpeg import read_frames, write_frames

def trim(image):
    img = np.frombuffer(image, np.uint8).reshape(meta['size'][1],
                                                 meta['size'][0], -1)
    return np.ascontiguousarray(img[128:-128, 128:-128, :] ) # value tested : 8, 16, 32, 64, 128 (greater value make image smaller)

video_file = 'merge_audio_ffmpeg.mp4'
fps_v = '10' # 60 for production
output_file = 'trim.mp4'

reader = read_frames(video_file)
meta = reader.__next__()

writer = write_frames(output_file, audio_path = video_file,
                      size = meta['size'], fps = meta['fps'],
                      input_params = ['-y', ],
                      output_params = ['-r', fps_v, ] )
writer.send(None)

for frame in reader:
    filter = trim(frame)
    writer.send(filter)

writer.close()

IPython.display.Video(output_file, embed = True)
```

**result**

https://github.com/imageio/imageio-ffmpeg/assets/2418295/e2ac000a-ba6b-446b-b876-abadf86c4ef1

**expected result**
the same function trim(image) that run with moviepy

https://github.com/imageio/imageio-ffmpeg/assets/2418295/967f5747-ee74-4d13-a2d3-2f345c782795

how to face it using imageio-ffmpeg ?

best regards

**Comment by almarklein** [comment]
As the output size you specify the input size, but you make the frames smaller.

Listen, creating an issue to ask a question about the usage of a library is fine, but this is not a free helpdesk. I'd recommend trying harder yourself to solve the problems you face. Check the shapes of the frames, use print statements in the code, display intermediate results, learn how to debug the code. That way you will learn far more.
