### ISSUE TITLE
logger warnings are a bit much

### ISSUE THREAD

**Issue by christopherhesse** [imageio/imageio-ffmpeg#18]
There is a lot of warning output from the logger, and no apparent way to disable it.

There's a python library for warnings in the stdlib: https://docs.python.org/3/library/warnings.html

Using this instead of the root logger would make it easier to discard the logging warnings.

**Comment by christopherhesse** [comment]
Currently I have to do `logging.getLogger().setLevel(logging.ERROR)` which disables anything else using the logger package.

**Comment by christopherhesse** [comment]
My bad, it's actually not the root logger, it might be worth considering the warnings library though.

**Comment by almarklein** [comment]
Would this help?
```py
logging.getLogger("imageio_ffmpeg").setLevel(logging.ERROR)
```

**Comment by christopherhesse** [comment]
Sorry, that's what I started doing after I figured out which logger was being used.  I was saying that the warnings package might be a better fit for warnings like this, but I don't care that much since it's disable-able.  Thanks for the answer!
