### ISSUE TITLE
Custom number of bytes per pixel in read_frames

### ISSUE THREAD

**Issue by mastak** [imageio/imageio-ffmpeg#24]
Y′UV format can have a different number of bytes per pixel:
https://en.wikipedia.org/wiki/YUV#Converting_between_Y%E2%80%B2UV_and_RGB

And some variants such as:
```
YUV420p   6 bytes per 4 pixels
```
can't be set as `bpp` for `read_frames`. As a result, there is broken `framesize` and we have RuntimeError with `End of file reached before full frame could be read`

**Comment by almarklein** [comment]
Closed by #25
