### ISSUE TITLE
FFMPEG reader fails after KeyboardInterrupt

### ISSUE THREAD

**Issue by sorenrasmussen** [imageio/imageio-ffmpeg#4]
After a manual KeyboardInterrupt ([Ctrl]+[c]), reading a frame with (index > 0) causes an FFMPEG error.

```
import imageio
reader = imageio.get_reader("imageio:cockatoo.mp4",format="ffmpeg")

#reader.get_data(2) #Initializing the reader by reading some frame here will cause the error to go away

try:
    input("Do a manual KeyboardInterrupt [Ctrl]+[c] (raising an error with code won't trigger the error)")
except:
    print(reader.get_data(1)) #Reading some frame, n>0 fails.
    print(reader.get_data(0)) #Reading frame 0 works fine.
```

**System:**
Imageio 2.4.1
Python 3.6.5
FFMPEG 3.2.4
Linux 64bit

**Comment by almarklein** [comment]
Moved this issue to the new `imageio_ffmpeg` repo.

**Comment by almarklein** [comment]
I tried this: https://stackoverflow.com/a/39174578/2271927  but the solution for Windows does not seem to work.

**Comment by almarklein** [comment]
Looking into this now and having a facepalm moment when I realized it's the ffmpeg process stopping because the interrupt propagates to the subprocesses 🤦‍♂

**Comment by almarklein** [comment]
https://stackoverflow.com/questions/5045771
