### ISSUE TITLE
Find ffmpeg in frozen applications

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio-ffmpeg#5]
When this lib is included in a frozen application, the ffmpeg executable must be shipped along too. We should:

* Perhaps provide a simple function that can be used in the freeze script to copy the ffmpeg exe.
* Make `get_ffmpeg_exe()` look in the frozen application directory.

While we don't have this, please copy the ffmpeg executable yourself, and use the `IMAGEIO_FFMPEG_EXE` environment variable to point to it.

**Comment by almarklein** [comment]
This relates to https://github.com/imageio/imageio/issues/271 cc @paulmueller

**Comment by paulmueller** [comment]
I think this is already implemented. Simply use the ``--package-dir`` option and the ffmpeg binary will be downloaded to the package directory / resources.

``imageio_download_bin --package-dir ffmpeg``

For PyInstaller, at least, the following built-in hook makes sure the binaries end up in the final distribution build:
https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-imageio.py

reference: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/blob/master/appveyor.yml#L82

**Comment by almarklein** [comment]
Yeah the `imageio_download_bin` will no longer work for ffmpeg. So to summarize:

* This new imageio_ffmpeg library will have the ffmpeg exe included in its "binaries" subdirectory. That is, on the platforms for which there are wheels.
* We'd need to add a hook to PyInstaller, quite similar to the one you linked, I suppose.
* We might need to add a little code in the [get_ffmpeg_exe() function](https://github.com/imageio/imageio-ffmpeg/blob/master/imageio_ffmpeg/_utils.py#L13) to look in alternative places when frozen?

> What about source tarballs on PyPI? Will they also contain the binary?

No, only the wheels. And there will still be a tarball on Pypi, so you can (surely pip has a flag for that?) install the lib without the binary, and supply one yourself.

**Comment by paulmueller** [comment]
I will create a PR for the hook and let you know how things work out. I believe that there will be no problem, if we use ``pgk_resources``.

**Comment by almarklein** [comment]
That would be great!

**Comment by marnunez** [comment]
Just a reminder, mostly for my future self, for when I inevitably forget it: those who installed imageio-ffmpeg with conda have **no  ffmpeg** binary under the "resources" folder. Modify the hook or use pip instead of conda.

**Comment by paulmueller** [comment]
Sorry for replying just now. I did a quick check and it looks like this is already implemented with `pkg_resources`. So it should work. Doesn't it?

**Comment by almarklein** [comment]
I guess so, but this has not yet been confirmed.

**Comment by paulmueller** [comment]
For me it works fine on Windows. Currently there is only https://github.com/imageio/imageio/issues/766 in the way.

**Comment by paulmueller** [comment]
It also works on linux. I think this one can be closed.

**Comment by almarklein** [comment]
Thanks for the confirmation, we can close!
