### ISSUE TITLE
encode with audio using file path

### ISSUE THREAD

**Issue by ksmoore17** [imageio/imageio-ffmpeg#50]
Hi I made a simple change to the write_frames method to allow for an audio file to be provided. Is it within scope / would you like a pull request?

https://github.com/pierogis/imageio-ffmpeg/blob/audio/imageio_ffmpeg/_io.py#L377-L386

**Comment by almarklein** [comment]
Hi, that's interesting. I think it could be useful for others, so if we can add this without complicating the API and/or source too much, it's probably worth it, yes!

**Comment by ksmoore17** [comment]
Ok gotcha, I will also add a param to provide the audio codec for output and look into using an audio buffer (like the video) as an alternative to a file.

**Comment by almarklein** [comment]
Closed by #51
