### ISSUE TITLE
Aarch64 wheel is missing on PyPi

### ISSUE THREAD

**Issue by odidev** [imageio/imageio-ffmpeg#52]
I have seen that the aarch64 wheel is missing in Pypi. It will be useful if the aarch64 wheel is released as -

- The Arm architecture has been available on AWS (Graviton2) for about 2 years now and has seen a lot of adoption by various organizations. The install base of Arm users is growing at a rapid pace.

- Oracle cloud will be releasing Arm based Compute Shapes in the future. Please [see](https://www.anandtech.com/show/16100/oracle-announces-upcoming-cloud-compute-instances-ice-lake-and-milan-a100-and-altra#:~:text=OCI%E2%80%99s%20Arm%20instances%20will%20clock%20as%20high%20as,%E2%80%93%20OCI%20is%20refreshing%20its%20GPU%20compute%20instances)

- Generally, there is a lot of momentum behind various products switching to Arm based CPUs. For example, the Microsoft surface Pro X is an Arm based device.

 
@almarklein Please let me know your interest in releasing aarch64 wheels. I can help in this. To start with can you please suggest the steps you are using for building the wheel.

**Comment by odidev** [comment]
Arm64 binary is available in the form of tar [here](https://johnvansickle.com/ffmpeg/)

I have followed the following steps to create and test the wheel for aarch64 in **quay.io/pypa/manylinux2014_aarch64** docker- 

- Downloaded and untared the [ffmpeg-4.2.2-arm64](https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.2.2-arm64-static.tar.xz) tar file.

- Cloned [imageio-binaries](https://github.com/imageio/imageio-binaries)  and [imageio-ffmpeg](https://github.com/imageio/imageio-ffmpeg) package. Also install **invoke** using pip.

- Renamed the binary to **ffmpeg-linuxaarch64-v4.2.2** and placed inside **imageio-binaries/ffmpeg/** folder.

- Did the following modification in [file](https://github.com/imageio/imageio-ffmpeg/blob/master/imageio_ffmpeg/_definitions.py) to create a wheel for aarch64.

**Commit Link** - https://github.com/odidev/imageio-ffmpeg/commit/e43f6e175393e689a745c485a5e629c553e13bc3

- Ran the **/opt/python/cp36-cp36m/bin/python -m invoke build** command in order to build the wheel for aarch64.

- Installed the created wheel and some dependencies like psutil, pytest-cov, pytest which are used for testing.

- Place the binary to **imageio-ffmpeg/imageio_ffmpeg/binaries/** folder and add execute permission.

- Then ran **/opt/python/cp36-cp36m/bin/python -m invoke test** command to test the wheel.

Could you please suggest further blockers in releasing the wheel for aarch64?

**Comment by odidev** [comment]
I have raised the [PR](https://github.com/imageio/imageio-ffmpeg/pull/53) here and also raised the [PR](https://github.com/imageio/imageio-binaries/pull/17) for the binary in [imageio-binaries](https://github.com/imageio/imageio-binaries)

**Comment by almarklein** [comment]
Thanks! I just pushed a new release to pypi, so if all is well, you should be able to `pip install imageio-ffmpeg` on aarrch64.
